### ISSUE TITLE
Fix spelling

### ISSUE THREAD

**Issue by fouadalnahhal** [muhammadelhelaly/JsonBasedLocalizationInDotNetCore6#1]
https://github.com/muhammadelhelaly/JsonBasedLocalizationInDotNetCore6/blob/eb176fd21fa274fda1728fecb188a88504097368/JsonBasedLocalization.Web/JsonStringLocalizer.cs#L64

**Comment by muhammadelhelaly** [comment]
Issue resolved, many thanks :)
